# Changes here will be overwritten by Copier
_commit: 4.3.0
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: douglas.winter@diamond.ac.uk
author_name: Douglas Winter
component_lifecycle: experimental
component_owner: group:default/sscc
component_type: service
description: Microservice for reading HDF5 data and serving it via REST, aimed at
    performance and concurrency
distribution_name: hdf5-reader-service
docker: true
docker_debug: true
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: hdf5_reader_service
pypi: true
repo_name: hdf5-reader-service
strict_typing: true
type_checker: pyright
