on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        description: If true, pushes image to container registry

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          # Need this to get version number from last tag
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export to Docker local cache
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          # Need load and tags so we can test it below
          load: true
          tags: tag_for_testing

      - name: Test cli works in cached runtime image
        run: docker run --rm tag_for_testing --version

      - name: Create tags for publishing image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Push cached image to container registry
        if: inputs.publish && github.ref_type == 'tag'
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        # This does not build the image again, it will find the image in the
        # Docker cache and publish it
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  helm_publish:
    name: Publish helm chart
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4

      - name: Install helm
        uses: Azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: install

      - name: Login to gcr using helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | \
            helm registry login ghcr.io \
            --username ${{ github.repository_owner }} \
            --password-stdin

      - name: Package and publish helm chart
        run: |
          CHART_DIR=helm/hdf5-reader-service
          CHART_NAME=hdf5-reader-service
          VERSION=${GITHUB_REF##*/}
          helm dependencies update $CHART_DIR
          helm package $CHART_DIR --version $VERSION --app-version $VERSION -d /tmp/
          helm push /tmp/${CHART_NAME}-${VERSION}.tgz oci://ghcr.io/diamondlightsource/charts
