name: Container CI

on:
  push:
    branches:
    - master
  release:
    types: [published]

jobs:
  build-image:
    timeout-minutes: 60

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate image tags
        id: tagger
        run: |
          # tag is branch name or tag if there is a tag
          echo ::set-output name=image_tag::${GITHUB_REF##*/}
          echo ::set-output name=do_push::true
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
          key: ${{ runner.os }}-hdf5-reader-service-${{ github.sha }}
          restore-keys: ${{ runner.os }}-hdf5-reader-service-
      
      - name: Log in to Github Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/hdf5-reader-service
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - id: read-docker-image-identifiers
        name: Read Docker Image Identifiers
        run: echo ::set-env name=IMAGE_REPOSITORY::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

      - name: Run build (base container)
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.output.name }}
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_REPOSITORY }}:${{ steps.tagger.outputs.image_tag }}
          target: base
          cache-from: type=local,src=~/cache
          cache-to: type=local,dest=~/cache
