name: Link Check

on:
  schedule:
    # Run every Monday at 8am to check URL links still resolve
    - cron: "0 8 * * MON"

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Build docs
        uses: dls-controls/pipenv-run-action@v1
        with:
          python-version: "3.9"
          pipenv-run: docs -b linkcheck
